days.push(['Lem', 'Thul', 'Thul', 'Tir', 'Um', 'Ral', 'Ort', 'Tir', 'Shael', 'Sol', 'Eth', 'Tir', 'Shael', 'Tir', 'Thul']);
days.push(['Tal', 'Dol', 'Eld', 'Eth', 'Hel', 'Tal', 'Eth', 'Tal', 'Ral', 'Amn', 'El', 'Amn', 'Tal', 'Ith', 'Lum']);
days.push(['Ort', 'Amn', 'El', 'Sol', 'Nef', 'Ort', 'Thul', 'Amn', 'Ort', 'Tal', 'Ort', 'Thul', 'Lum', 'Eth', 'Eth']);
days.push(['Ort', 'El', 'Sol', 'Dol', 'Shael', 'Ral', 'Tir', 'Sol', 'Eth', 'Sol', 'Hel', 'Eth', 'Thul', 'Hel', 'Sol']);
days.push(['Sol', 'Thul', 'Nef', 'Eld', 'Lum', 'Tal', 'Ith', 'Ort', 'Eth', 'Ral', 'Sol', 'El', 'Amn', 'Tal', 'Ral']);
days.push(['Ort', 'Ort', 'Tal', 'Amn', 'Ko', 'Eth', 'Hel', 'Ral', 'Amn', 'Ort', 'Amn', 'Eth', 'Io', 'Ort', 'Sol']);
days.push(['Tal', 'Tal', 'Sol', 'Nef', 'Ith', 'Amn', 'Amn', 'Amn', 'Ort', 'Dol', 'Ith', 'Tal', 'Lum', 'Sol', 'Ort']);
days.push(['Amn', 'Shael', 'Shael', 'Amn', 'Ort', 'Ort', 'Ral', 'Dol', 'Nef', 'Amn', 'Tal', 'Tal', 'Ort', 'Thul', 'Eth']);
days.push(['Ith', 'Tir', 'Hel', 'Tal', 'Amn', 'Ith', 'Sol', 'Shael', 'Ith', 'Ith', 'Sol', 'Ral', 'Sol', 'Tal', 'Ral']);
days.push(['Tal', 'Tir', 'Hel', 'Ort', 'Ort', 'Ort', 'Shael', 'Ort', 'Ral', 'Eth', 'Hel', 'Ort', 'Ith', 'Eth', 'Hel']);
days.push(['Ral', 'Ral', 'Amn', 'Ith', 'Amn', 'Tal', 'Pul', 'Eld', 'Thul', 'Tal', 'Nef', 'Fal', 'Thul', 'Lum', 'Eth']);
days.push(['Sol', 'Tal', 'Ort', 'Amn', 'Ort', 'Ral', 'Thul', 'Tal', 'El', 'Lem', 'Amn', 'Ral', 'Dol', 'El', 'Shael']);
days.push(['Amn', 'Tal', 'Amn', 'Shael', 'Ral', 'Ort', 'Shael', 'Shael', 'Tal', 'Hel', 'Shael', 'Eth', 'Ort', 'Hel', 'Ort']);
days.push(['Sol', 'Tal', 'Ith', 'Nef', 'Ort', 'Thul', 'Shael', 'Amn', 'Nef', 'Hel', 'Nef', 'Dol', 'Ral', 'Nef', 'El']);
days.push(['Eth', 'Tir', 'Eth', 'Hel', 'Ort', 'Shael', 'El', 'Ral', 'Tal', 'Eth', 'Nef', 'Eth', 'Tal', 'Ort', 'Nef']);
days.push(['Thul', 'Eth', 'Shael', 'Ral', 'Ort', 'Nef', 'Hel', 'Gul', 'Io', 'Tir', 'Thul', 'Eth', 'Tir', 'Nef', 'Dol']);
days.push(['Ral', 'Tir', 'Ort', 'Amn', 'Ral', 'Hel', 'Thul', 'Lem', 'Ith', 'Ort', 'Ith', 'Eth', 'Eld', 'Lum', 'Ral']);
days.push(['Thul', 'Eld', 'Amn', 'Eth', 'Amn', 'Ral', 'Nef', 'Tal', 'Eld', 'Eth', 'Ko', 'Eld', 'Ith', 'Ral', 'Tal']);
days.push(['Nef', 'Fal', 'Ort', 'Ral', 'Hel', 'Shael', 'Ort', 'Tal', 'Tal', 'Ort', 'Dol', 'Tir', 'Tal', 'Io', 'Eld']);
days.push(['Thul', 'Hel', 'Ko', 'Tir', 'Eth', 'Tal', 'Ral', 'Shael', 'Ort', 'Dol', 'Ral', 'Eth', 'Sol', 'Ral', 'Amn']);
days.push(['Dol', 'Ort', 'Ort', 'Tal', 'Ko', 'Um', 'Eth', 'Hel', 'Ort', 'El', 'Amn', 'Ral', 'Sol', 'Nef', 'Ith']);
days.push(['Amn', 'Tal', 'Ort', 'Dol', 'Ith', 'Tal', 'Tal', 'Tal', 'Tal', 'Tir', 'Ith', 'Tal', 'Amn', 'Eth', 'Eth']);
days.push(['Ist', 'Amn', 'Dol', 'Amn', 'Eld', 'Tir', 'Ral', 'Amn', 'Ort', 'Tal', 'Tal', 'Tir', 'Hel', 'Shael', 'Lem']);
days.push(['Tal', 'Nef', 'Tir', 'Ort', 'Ith', 'Ko', 'Amn', 'Tir', 'Dol', 'Thul', 'Io', 'Sol', 'Eth', 'Tal', 'Eth']);
days.push(['Ith', 'Tal', 'Thul', 'Ort', 'Ral', 'Ort', 'Nef', 'Dol', 'Amn', 'Ral', 'Tal', 'Nef', 'Ral', 'Ort', 'Eth']);
days.push(['Sol', 'Nef', 'Ith', 'Ith', 'Tir', 'Ort', 'Thul', 'Tir', 'Thul', 'Mal', 'Ort', 'Ral', 'Thul', 'Tal', 'Eth']);
days.push(['Tal', 'Thul', 'Amn', 'Lum', 'Shael', 'Ith', 'Ith', 'Tal', 'Amn', 'Dol', 'Amn', 'Amn', 'Ort', 'Amn', 'Eth']);
days.push(['Dol', 'Tal', 'El', 'Ort', 'Ort', 'Tal', 'Shael', 'Tal', 'Ort', 'Tal', 'Dol', 'El', 'Ort', 'Amn', 'Amn']);
days.push(['Tal', 'Amn', 'Ort', 'Tal', 'Ral', 'Ort', 'Ort', 'Ral', 'Ort', 'Eth', 'Eth', 'Amn', 'Sol', 'Amn', 'Tal']);
days.push(['Amn', 'Sol', 'Eth', 'El', 'Tal', 'Ist', 'Io', 'Tal', 'Thul', 'Ral', 'El', 'Tal', 'Hel', 'Ral', 'Ort']);
days.push(['Ith', 'Nef', 'Thul', 'Sol', 'Hel', 'Tal', 'Ort', 'Amn', 'Amn', 'Amn', 'Shael', 'Dol', 'Ral', 'Amn', 'Ort']);
days.push(['Thul', 'Ort', 'Ort', 'Eth', 'Shael', 'Amn', 'Ort', 'Tir', 'Tal', 'Tal', 'Amn', 'Lum', 'Shael', 'El', 'Dol']);
days.push(['Ort', 'Eth', 'Ral', 'Eth', 'Thul', 'Tal', 'Ort', 'Hel', 'Sol', 'Eth', 'Thul', 'Dol', 'Ith', 'Amn', 'Ral']);
days.push(['El', 'Thul', 'Eth', 'Tir', 'Shael', 'Thul', 'Eth', 'Ith', 'Sol', 'Fal', 'Ral', 'Sol', 'Ral', 'Thul', 'Ral']);
days.push(['Ort', 'Thul', 'Eth', 'Ort', 'El', 'Amn', 'Tir', 'Tal', 'Tal', 'Ral', 'El', 'Ral', 'Sol', 'Ith', 'Tal']);
days.push(['Ort', 'Shael', 'Ral', 'Thul', 'Thul', 'Shael', 'Io', 'Tal', 'Sol', 'Hel', 'Hel', 'Thul', 'Ral', 'Lem', 'Mal']);
days.push(['Sol', 'Pul', 'Tal', 'Eth', 'Thul', 'Thul', 'Lum', 'Tir', 'Lem', 'Io', 'Thul', 'Tal', 'Tir', 'Eth', 'Ral']);
days.push(['Ort', 'Eth', 'Eth', 'Tal', 'Tal', 'Ort', 'Ort', 'Tir', 'Ort', 'Sol', 'El', 'Hel', 'Fal', 'Hel', 'Tal']);
days.push(['Shael', 'Eth', 'Thul', 'Tal', 'Eld', 'Nef', 'Eth', 'Eth', 'Ral', 'Tir', 'Ort', 'Hel', 'Eth', 'Tal', 'Eth']);
days.push(['Thul', 'Amn', 'El', 'Io', 'Amn', 'Eth', 'Ort', 'Shael', 'Tir', 'Amn', 'Tir', 'Lum', 'Ort', 'Ort', 'Ort']);
days.push(['Ort', 'Thul', 'Ort', 'Thul', 'Thul', 'Eth', 'Ort', 'Ort', 'Tal', 'Amn', 'Io', 'Hel', 'Tir', 'Ort', 'Hel']);
days.push(['Sol', 'Amn', 'Amn', 'Ith', 'Amn', 'Eth', 'Ral', 'Tir', 'Ko', 'Ort', 'Amn', 'Tal', 'Tal', 'Eth', 'Fal']);
days.push(['Amn', 'Tal', 'Ral', 'Tal', 'Dol', 'Thul', 'Amn', 'Ort', 'El', 'Eth', 'Io', 'Sol', 'Tal', 'El', 'Shael']);
days.push(['Thul', 'Ort', 'Eth', 'Shael', 'Ort', 'Ith', 'Ko', 'Eth', 'Eld', 'Shael', 'Shael', 'Ral', 'Sol', 'Tal', 'Ral']);
days.push(['Ort', 'Shael', 'Nef', 'Ort', 'Tir', 'Ort', 'Thul', 'Ort', 'Tal', 'Shael', 'Amn', 'Ort', 'Dol', 'Shael', 'Ort']);
days.push(['Tal', 'Shael', 'Ral', 'Shael', 'Thul', 'Tal', 'Eth', 'Tal', 'Mal', 'Eth', 'Amn', 'Shael', 'Ith', 'Amn', 'Eth']);
days.push(['Thul', 'Ort', 'Tal', 'Tal', 'Dol', 'El', 'Ort', 'Lum', 'Tir', 'Lum', 'Tir', 'Tir', 'Tal', 'Ort', 'Thul']);
days.push(['Nef', 'Ort', 'Tal', 'Eth', 'Eth', 'Fal', 'Sol', 'Ral', 'Fal', 'Eld', 'Ort', 'Sol', 'Ith', 'Shael', 'Tal']);
days.push(['Amn', 'Dol', 'Ral', 'Sol', 'Ith', 'Nef', 'Hel', 'Ort', 'Eth', 'Ort', 'Thul', 'Amn', 'Eth', 'Tir', 'Tir']);
days.push(['Ort', 'Ort', 'Ral', 'Eth', 'Ort', 'Sol', 'Tal', 'Amn', 'Dol', 'Sol', 'Ith', 'Tal', 'Ral', 'Amn', 'Eth']);
days.push(['Nef', 'Tir', 'Amn', 'Shael', 'Eth', 'Thul', 'Ort', 'Ral', 'Ort', 'Dol', 'Tal', 'Thul', 'El', 'Amn', 'Shael']);
days.push(['Nef', 'Tal', 'Ort', 'El', 'Eth', 'Tal', 'Tal', 'Tal', 'Ort', 'Tal', 'Tal', 'Tal', 'Sol', 'El', 'Dol']);
days.push(['Eth', 'Ort', 'Amn', 'Ral', 'Tir', 'Thul', 'Ort', 'El', 'Eth', 'Eth', 'Lum', 'Ort', 'Pul', 'Lum', 'Sol']);
days.push(['Ort', 'Ith', 'Shael', 'Ith', 'Ral', 'Tal', 'Tal', 'Ort', 'Eth', 'Amn', 'Amn', 'Amn', 'Tir', 'Ort', 'Thul']);
days.push(['Ith', 'Eth', 'Ort', 'Thul', 'Ral', 'Dol', 'Ral', 'Nef', 'Shael', 'Io', 'Amn', 'Eth', 'Tal', 'Tal', 'Mal']);
days.push(['Thul', 'Ko', 'Shael', 'Tal', 'Um', 'Amn', 'Tal', 'Shael', 'Tal', 'Thul', 'Ko', 'Amn', 'Eth', 'Hel', 'Tal']);
days.push(['Shael', 'Tal', 'Tir', 'Thul', 'Sol', 'Thul', 'Tir', 'Eth', 'Shael', 'Thul', 'Ort', 'Ort', 'Tal', 'Ith', 'Dol']);
days.push(['Lum', 'Sol', 'Io', 'Eth', 'Tir', 'Dol', 'Sol', 'Ith', 'Dol', 'Ort', 'Tal', 'Eth', 'Tir', 'Amn', 'Ort']);
days.push(['Tal', 'Ort', 'Ral', 'Sol', 'Sol', 'Shael', 'Shael', 'Sol', 'Amn', 'Tal', 'Tal', 'Sol', 'Tir', 'Ral', 'Amn']);
days.push(['Tal', 'Tal', 'Thul', 'Ort', 'Eld', 'Tal', 'Ral', 'Ith', 'Tal', 'Thul', 'Ral', 'El', 'Eth', 'Thul', 'Ith']);
days.push(['Shael', 'Eth', 'Sol', 'Amn', 'Mal', 'Ith', 'Thul', 'Sol', 'Amn', 'Gul', 'Eth', 'Hel', 'Fal', 'Ort', 'Ral']);
days.push(['Tal', 'Dol', 'Ral', 'Amn', 'Sol', 'Thul', 'Io', 'Nef', 'Amn', 'Eth', 'Eth', 'Tir', 'Ral', 'Tal', 'Shael']);
days.push(['Ort', 'Tir', 'Ort', 'Tir', 'Hel', 'Amn', 'Thul', 'Shael', 'Ith', 'Ort', 'Amn', 'Ral', 'Tal', 'Hel', 'Thul']);
days.push(['Lem', 'Ith', 'Sol', 'Hel', 'Ort', 'Lum', 'Ort', 'Ral', 'Ort', 'Eth', 'Nef', 'Sol', 'Tal', 'Tir', 'Eth']);
days.push(['Ort', 'Sol', 'Ral', 'Eth', 'Nef', 'Ith', 'Ort', 'Shael', 'Ko', 'Thul', 'Thul', 'Eth', 'Eld', 'Hel', 'Thul']);
days.push(['El', 'Tal', 'Eld', 'El', 'Tal', 'Thul', 'Eth', 'Thul', 'Sol', 'Amn', 'Eld', 'Dol', 'Amn', 'Io', 'Ort']);
days.push(['Sol', 'Tal', 'Hel', 'Ort', 'Tal', 'Tir', 'Amn', 'Amn', 'Amn', 'Ral', 'Shael', 'Thul', 'Ort', 'Ral', 'Thul']);
days.push(['Thul', 'Amn', 'Eth', 'Sol', 'Tal', 'Amn', 'Ith', 'Amn', 'Amn', 'Ko', 'Um', 'Ort', 'Tal', 'Hel', 'Ort']);
days.push(['Sol', 'Thul', 'Dol', 'Sol', 'Eth', 'Ort', 'Sol', 'Dol', 'Tal', 'Ko', 'Tal', 'Eth', 'Tal', 'Tir', 'Ko']);
days.push(['Tal', 'Tal', 'Amn', 'Dol', 'Dol', 'Ith', 'Sol', 'Shael', 'Tal', 'Nef', 'Ort', 'Ort', 'Ith', 'Lum', 'Dol']);
days.push(['Eth', 'Ort', 'Tal', 'Tir', 'Thul', 'Nef', 'Tir', 'Shael', 'Amn', 'Shael', 'Amn', 'Lum', 'Dol', 'Ort', 'Eth']);
days.push(['Ort', 'Ort', 'Ort', 'Tal', 'Tal', 'Tal', 'Thul', 'Thul', 'Ith', 'Ith', 'Amn', 'Amn', 'Eth', 'Dol', 'Lem']);
days.push(['Sol', 'Sol', 'Sol', 'Sol', 'Ort', 'Ort', 'Eth', 'Eth', 'Thul', 'Dol', 'Ith', 'Amn', 'Tal', 'Fal', 'Um']);
days.push(['Ort', 'Ort', 'Ort', 'Eth', 'Eth', 'Eth', 'Tal', 'Tal', 'Amn', 'Amn', 'Ral', 'Ral', 'Shael', 'Lum', 'Nef']);
days.push(['Dol', 'Dol', 'Dol', 'Tal', 'Tal', 'Tal', 'Ort', 'Ort', 'Ort', 'Eth', 'Eth', 'Nef', 'Nef', 'Shael', 'Eld']);
days.push(['Fal', 'Fal', 'Thul', 'Thul', 'Ith', 'Ith', 'Ort', 'Ort', 'Shael', 'Shael', 'Um', 'Eld', 'Ko', 'Sol', 'Nef']);
days.push(['Ith', 'Ith', 'Ith', 'Sol', 'Sol', 'Tal', 'Tal', 'Eth', 'Ral', 'Lem', 'Ort', 'Ko', 'Dol', 'Amn', 'Eld']);
days.push(['Ral', 'Ral', 'Ort', 'Ort', 'Nef', 'Nef', 'El', 'Thul', 'Io', 'Sol', 'Fal', 'Shael', 'Eth', 'Tal', 'Ith']);
days.push(['Ith', 'Ith', 'Ith', 'Ith', 'Shael', 'Shael', 'Dol', 'Dol', 'Ort', 'Amn', 'Hel', 'Lum', 'Tal', 'Ral', 'Tir']);
days.push(['Thul', 'Thul', 'Thul', 'Ith', 'Ith', 'Dol', 'Dol', 'Shael', 'Sol', 'Ort', 'Eth', 'Nef', 'Eld', 'Amn', 'Lem']);
days.push(['Sol', 'Sol', 'Sol', 'Eth', 'Eth', 'Eth', 'Tir', 'Tir', 'Tal', 'Tal', 'Amn', 'Ort', 'Dol', 'Shael', 'Ral']);
days.push(['Shael', 'Shael', 'Shael', 'Amn', 'Amn', 'Ral', 'Ral', 'Thul', 'Thul', 'Ith', 'Um', 'Lum', 'Fal', 'Tal', 'El']);
days.push(['Amn', 'Amn', 'Amn', 'El', 'El', 'Thul', 'Thul', 'Lum', 'Lum', 'Sol', 'Tal', 'Dol', 'Ith', 'Hel', 'Shael']);
days.push(['Ral', 'Ral', 'Ral', 'Sol', 'Sol', 'Sol', 'Tir', 'Tir', 'Amn', 'Amn', 'Ort', 'Eld', 'Tal', 'Ith', 'Um']);
days.push(['Ort', 'Ort', 'Ort', 'Ort', 'Ort', 'Ral', 'Ral', 'Thul', 'Thul', 'Sol', 'Eth', 'Amn', 'Tal', 'El', 'Ith']);
days.push(['Tal', 'Tal', 'Tal', 'Tal', 'Eth', 'Eth', 'Eth', 'Ort', 'Ort', 'Amn', 'Amn', 'Thul', 'Thul', 'Sol', 'Hel']);
days.push(['Ort', 'Ort', 'Ort', 'Thul', 'Thul', 'Tal', 'Tal', 'Sol', 'Sol', 'Hel', 'Nef', 'Amn', 'Tir', 'Lum', 'El']);
days.push(['Tal', 'Tal', 'Tal', 'Sol', 'Sol', 'Amn', 'Amn', 'Eth', 'Dol', 'Thul', 'Ral', 'Shael', 'Lum', 'Ith', 'Nef']);
days.push(['Tal', 'Tal', 'Tal', 'Tal', 'Nef', 'Nef', 'Tir', 'Tir', 'Eth', 'Hel', 'Thul', 'Amn', 'Ral', 'Shael', 'Ort']);
days.push(['Ort', 'Ort', 'Tal', 'Tal', 'Ral', 'Ral', 'Amn', 'Amn', 'Thul', 'Thul', 'Ko', 'Sol', 'Io', 'Dol', 'Nef']);
days.push(['Amn', 'Amn', 'Amn', 'Thul', 'Thul', 'Thul', 'Eth', 'Eth', 'Shael', 'Shael', 'Tal', 'Ral', 'Sol', 'Ist', 'Io']);
days.push(['Eth', 'Eth', 'Eth', 'Tal', 'Tal', 'Sol', 'Sol', 'Amn', 'Ith', 'Ort', 'Lem', 'Ral', 'Lum', 'Thul', 'Eld']);
days.push(['Amn', 'Amn', 'Amn', 'Sol', 'Sol', 'Shael', 'Shael', 'Tal', 'Tal', 'Eth', 'Nef', 'Thul', 'Ral', 'Ith', 'Ort']);
days.push(['Tir', 'Tir', 'Tal', 'Tal', 'Eth', 'Eth', 'Thul', 'Thul', 'Amn', 'Ort', 'Sol', 'Nef', 'Shael', 'Eld', 'Dol']);
days.push(['Ort', 'Ort', 'Ort', 'Tir', 'Tir', 'Tal', 'Tal', 'Ral', 'Ral', 'Sol', 'Sol', 'Eth', 'Thul', 'Amn', 'Ko']);
days.push(['Amn', 'Amn', 'Amn', 'Ith', 'Ith', 'Nef', 'Nef', 'Ort', 'Um', 'Eth', 'Lem', 'Hel', 'Thul', 'Ko', 'Tal']);
days.push(['Amn', 'Amn', 'Amn', 'Amn', 'Ral', 'Ral', 'Shael', 'Shael', 'Thul', 'Tal', 'Io', 'Dol', 'Um', 'Nef', 'Ist']);
days.push(['Nef', 'Nef', 'Nef', 'Amn', 'Amn', 'Fal', 'Tir', 'Shael', 'Eld', 'El', 'Dol', 'Mal', 'Tal', 'Io', 'Ith']);
days.push(['Ral', 'Ral', 'Ral', 'Thul', 'Thul', 'Hel', 'Hel', 'Eth', 'Eth', 'Io', 'Tir', 'Lem', 'Tal', 'Sol', 'Nef']);
days.push(['Amn', 'Amn', 'Amn', 'Amn', 'Tal', 'Tal', 'Ort', 'Ort', 'Shael', 'Shael', 'Eth', 'Eth', 'Ith', 'Sol', 'Ral']);
days.push(['Dol', 'Dol', 'Dol', 'Tal', 'Tal', 'Tal', 'Sol', 'Sol', 'Thul', 'Thul', 'Hel', 'Amn', 'Ith', 'Ral', 'Ort']);
days.push(['Tal', 'Tal', 'Tal', 'Ort', 'Ort', 'Ort', 'Sol', 'Sol', 'Shael', 'Nef', 'Hel', 'Thul', 'Io', 'Ral', 'Eth']);
days.push(['Tal', 'Tal', 'Tal', 'Nef', 'Nef', 'Amn', 'Amn', 'Ral', 'Ral', 'Lum', 'Eth', 'Dol', 'Ort', 'Thul', 'Um']);
days.push(['Tal', 'Tal', 'Tal', 'Nef', 'Nef', 'Io', 'Io', 'Eth', 'Eth', 'El', 'Shael', 'Dol', 'Amn', 'Lum', 'Thul']);
days.push(['Amn', 'Amn', 'Amn', 'Amn', 'Ort', 'Ort', 'Tal', 'Tal', 'Thul', 'Thul', 'Eth', 'Tir', 'Io', 'Ith', 'Dol']);
days.push(['Tal', 'Tal', 'Tal', 'Thul', 'Thul', 'Thul', 'Io', 'Dol', 'Sol', 'Lum', 'Mal', 'Ral', 'Eth', 'Ort', 'El']);
days.push(['Ral', 'Ral', 'Ral', 'Ort', 'Ort', 'Io', 'Io', 'Lum', 'Nef', 'Lem', 'Shael', 'Amn', 'Eth', 'Vex', 'Sol']);
days.push(['Thul', 'Thul', 'Thul', 'Tal', 'Tal', 'Dol', 'Dol', 'Sol', 'Sol', 'Fal', 'Shael', 'Ral', 'Eth', 'Amn', 'Nef']);
days.push(['Ort', 'Ort', 'Ort', 'Ort', 'Shael', 'Shael', 'Shael', 'Eth', 'Eth', 'Amn', 'Amn', 'Ko', 'Sol', 'Um', 'Ith']);
days.push(['Tal', 'Tal', 'Tal', 'Thul', 'Thul', 'Sol', 'Sol', 'Dol', 'Nef', 'Ral', 'Eth', 'Mal', 'Pul', 'Eld', 'Tir']);
days.push(['Ort', 'Ort', 'Dol', 'Dol', 'Tir', 'Tir', 'Amn', 'Ral', 'Pul', 'Nef', 'Hel', 'Mal', 'Tal', 'Eth', 'Eld']);
days.push(['Tal', 'Tal', 'Tal', 'Ko', 'Ko', 'Ort', 'Ort', 'Eth', 'Ith', 'Lum', 'Dol', 'Nef', 'Thul', 'Shael', 'Ral']);
days.push(['Amn', 'Amn', 'Amn', 'Sol', 'Fal', 'Tir', 'Ort', 'Nef', 'Io', 'Eth', 'Ral', 'Thul', 'Shael', 'El', 'Tal']);
days.push(['Ort', 'Ort', 'Ort', 'Ort', 'Ort', 'Eth', 'Eth', 'Eth', 'Ral', 'Ko', 'Sol', 'El', 'Tal', 'Hel', 'Amn']);

// var num = 15;
// var aaaa = shuffle(days.flat());
// days = [];
// let httt = '';
// let tmp = [];
// for (let i = 0; i < aaaa.length; i++) {
//   if (i % num == 0) {
//     httt += `days.push([`;
//     if (tmp.length > 0) {
//      days.push(tmp);
//     }
//     tmp = [];
//   }
//   tmp.push(aaaa[i]);
//   if (i == aaaa.length - 1) {
//     days.push(tmp);
//   }
//   httt += `'${aaaa[i]}'`;
//   if (i % num !== num - 1 && i != aaaa.length - 1) {
//     httt += `, `;
//   } else {
//     httt += `]);\n`;
//   }
// }
// console.log(httt);
