var days = [];
var total = [];

days.push(['Ral', 'Tal', 'Thul', 'Tal', 'Amn', 'Shael', 'Ith', 'Tal', 'El', 'Thul']);
days.push(['Eth', 'Thul', 'Eth', 'Amn', 'Ith', 'Tal', 'Ort', 'Ort', 'Ral', 'Sol']);
days.push(['Amn', 'Amn', 'Tal', 'Ort', 'Shael', 'Thul', 'Io', 'Thul', 'Tal', 'Amn']);
days.push(['Lum', 'Thul', 'El', 'Tal', 'Dol', 'Ist', 'Tal', 'Eth', 'Amn', 'Shael']);
days.push(['Tir', 'Thul', 'Dol', 'Ort', 'Tal', 'Thul', 'Amn', 'Ort', 'Nef', 'Amn']);
days.push(['Ort', 'Mal', 'Lum', 'Ort', 'Amn', 'Amn', 'Shael', 'Tal', 'Ral', 'Amn']);
days.push(['Ort', 'Eld', 'Ko', 'Dol', 'Tal', 'Thul', 'El', 'Amn', 'Hel', 'Eth']);
days.push(['Shael', 'Ort', 'Amn', 'Shael', 'Um', 'Eth', 'Amn', 'Shael', 'Ort', 'Tal']);
days.push(['Ral', 'Hel', 'Ort', 'Sol', 'Ith', 'Eth', 'Ort', 'Amn', 'Eth', 'Eth']);
days.push(['Dol', 'Lum', 'Eth', 'Ral', 'Sol', 'Dol', 'Ort', 'Ort', 'Ort', 'Ort']);
days.push(['Ort', 'Eth', 'Tir', 'Ral', 'El', 'Dol', 'Nef', 'Nef', 'Tir', 'El']);
days.push(['Hel', 'Tal', 'Hel', 'Ort', 'Amn', 'Ort', 'Eth', 'Eth', 'Tal', 'Amn']);
days.push(['Shael', 'Tal', 'Tal', 'Amn', 'Shael', 'Ort', 'Ral', 'Tir', 'Tal', 'Thul']);
days.push(['Tal', 'El', 'Ort', 'Shael', 'Eth', 'Thul', 'Thul', 'Ith', 'Tir', 'Ith']);
days.push(['Tir', 'Lum', 'Tir', 'Amn', 'Tal', 'Tir', 'Ort', 'Ort', 'Sol', 'Tir']);
days.push(['Ort', 'Thul', 'Amn', 'Ort', 'Lum', 'Ral', 'Eth', 'Tal', 'Hel', 'Amn']);
days.push(['Ral', 'Ral', 'Tal', 'Ort', 'Eth', 'Ith', 'Eld', 'Eth', 'Ort', 'Shael']);
days.push(['Tal', 'Io', 'Eth', 'Tir', 'Ort', 'Ith', 'Tal', 'Dol', 'Thul', 'Ral']);
days.push(['Sol', 'Nef', 'Ort', 'Dol', 'Tal', 'Tal', 'Eth', 'Ort', 'Tal', 'Shael']);
days.push(['Tal', 'Sol', 'Amn', 'Tal', 'Tir', 'Eth', 'Eld', 'Shael', 'Dol', 'Amn']);
days.push(['Tal', 'Tal', 'Tir', 'Ort', 'Sol', 'Ral', 'Ort', 'Eth', 'Ort', 'Hel']);
days.push(['Tal', 'Tal', 'Thul', 'Amn', 'Tal', 'Tal', 'Tal', 'Shael', 'Tir', 'Shael']);
days.push(['Thul', 'Tir', 'El', 'Nef', 'Amn', 'Hel', 'Hel', 'Nef', 'Amn', 'Ral']);
days.push(['Tal', 'Ort', 'Tir', 'Thul', 'Sol', 'Amn', 'Tal', 'Eth', 'Sol', 'Ral']);
days.push(['Tal', 'Thul', 'Tal', 'Ort', 'Eth', 'Ral', 'Tal', 'Ort', 'Ral', 'Ort']);
days.push(['Ith', 'Tir', 'Eth', 'Ort', 'Ith', 'Amn', 'Tal', 'Dol', 'Ith', 'Eth']);
days.push(['Ral', 'Ko', 'Ral', 'Ith', 'Tal', 'Tir', 'Lem', 'Eth', 'Eth', 'Ort']);
days.push(['Thul', 'Tal', 'Hel', 'El', 'Ort', 'Eth', 'Amn', 'Thul', 'Thul', 'Ort']);
days.push(['Dol', 'Tal', 'Amn', 'Eth', 'Eth', 'Amn', 'El', 'Hel', 'Fal', 'Lum']);
days.push(['Nef', 'Tal', 'Tir', 'Ort', 'Amn', 'Ith', 'Hel', 'Amn', 'Amn', 'Sol']);
days.push(['Thul', 'Eth', 'Shael', 'Sol', 'Ral', 'Dol', 'Ort', 'Ort', 'El', 'Fal']);
days.push(['Ort', 'Tir', 'Sol', 'Nef', 'Eth', 'Ral', 'Tal', 'Tal', 'Tir', 'Ral']);
days.push(['Ort', 'Eth', 'Tal', 'Tir', 'Shael', 'Ort', 'Eld', 'Eld', 'Thul', 'Shael']);
days.push(['Ort', 'Eth', 'Ort', 'Ith', 'Sol', 'Sol', 'Ort', 'Sol', 'Lum', 'Ort']);
days.push(['Amn', 'Thul', 'Tir', 'Ral', 'Ort', 'Amn', 'Eth', 'Tal', 'Amn', 'Shael']);
days.push(['Tir', 'Thul', 'Ral', 'Ral', 'Tal', 'Shael', 'Shael', 'Ort', 'Shael', 'Shael']);
days.push(['Tir', 'Eth', 'Tal', 'Hel', 'Shael', 'Ith', 'Eth', 'Ith', 'Tal', 'Thul']);
days.push(['Shael', 'Ort', 'Ith', 'Eth', 'Io', 'Ort', 'Eth', 'Ort', 'Ort', 'Dol']);
days.push(['Ith', 'Gul', 'Thul', 'Eld', 'Nef', 'Eth', 'Ort', 'Ort', 'El', 'Eth']);
days.push(['Amn', 'Ort', 'Sol', 'Tir', 'Dol', 'Um', 'Sol', 'Amn', 'Eth', 'Sol']);
days.push(['Ral', 'Tal', 'Nef', 'Tal', 'Thul', 'Dol', 'Ort', 'Sol', 'Ral', 'Amn']);
days.push(['Tal', 'Pul', 'Amn', 'Shael', 'Ort', 'Ral', 'Io', 'Eth', 'Tir', 'El']);
days.push(['Dol', 'Hel', 'Lum', 'Ral', 'Ort', 'Ral', 'Tal', 'Ort', 'Ko', 'El']);
days.push(['Ort', 'Tal', 'Ith', 'Tal', 'Nef', 'Ith', 'Sol', 'Amn', 'Lum', 'Eth']);
days.push(['Hel', 'Sol', 'Ort', 'Sol', 'Ith', 'Thul', 'Nef', 'Ral', 'Eth', 'Ith']);
days.push(['Sol', 'Tir', 'Tir', 'Tal', 'Nef', 'Sol', 'Amn', 'Ral', 'Tal', 'El']);
days.push(['Um', 'Sol', 'Tal', 'Nef', 'Ral', 'Ral', 'Dol', 'Ith', 'Lum', 'Nef']);
days.push(['Tal', 'Ort', 'Hel', 'Eld', 'Eth', 'Ort', 'Ort', 'Thul', 'Ort', 'Shael']);
days.push(['Tir', 'Ith', 'Ort', 'Thul', 'Amn', 'Tir', 'Tal', 'Io', 'Amn', 'Hel']);
days.push(['Dol', 'Sol', 'Tal', 'Ral', 'Sol', 'Ral', 'Sol', 'Eth', 'El', 'Ral']);
days.push(['Tal', 'Shael', 'Nef', 'Dol', 'Eth', 'Shael', 'Hel', 'Mal', 'Eth', 'Dol']);
days.push(['Hel', 'Tal', 'Tal', 'Nef', 'Thul', 'Amn', 'Dol', 'Ort', 'Tal', 'Eth']);
days.push(['Dol', 'Shael', 'Ort', 'Shael', 'Tir', 'Thul', 'Ral', 'Tal', 'Shael', 'El']);
days.push(['Tir', 'Tal', 'Tal', 'Ort', 'Lem', 'El', 'Fal', 'Tal', 'Thul', 'Ko']);
days.push(['Ko', 'Amn', 'Amn', 'Tal', 'Amn', 'Sol', 'Ith', 'Ral', 'Tal', 'Thul']);
days.push(['Io', 'Amn', 'Thul', 'Amn', 'Ral', 'Ort', 'Ral', 'Tal', 'El', 'Hel']);
days.push(['Ort', 'Ort', 'Thul', 'Amn', 'Shael', 'Amn', 'Amn', 'Eld', 'Sol', 'Lum']);
days.push(['Amn', 'Amn', 'Tir', 'Lum', 'Nef', 'Ral', 'Ral', 'Fal', 'Thul', 'Tal']);
days.push(['Tal', 'Lum', 'Ral', 'Ort', 'Ral', 'Ort', 'Tal', 'Shael', 'Amn', 'Thul']);
days.push(['Ort', 'Tal', 'El', 'Tal', 'Eth', 'Eth', 'Tal', 'Eld', 'Thul', 'Ral']);
days.push(['Ith', 'Amn', 'Sol', 'Ort', 'Nef', 'Thul', 'Eth', 'Tal', 'Ral', 'Sol']);
days.push(['Amn', 'Ort', 'Hel', 'Lem', 'Tal', 'Sol', 'Thul', 'Lem', 'Hel', 'Nef']);
days.push(['Tal', 'Thul', 'Tal', 'Dol', 'Ort', 'Ort', 'Eld', 'Shael', 'Tal', 'Ith']);
days.push(['Amn', 'Tal', 'Eth', 'Ith', 'Hel', 'Amn', 'Tal', 'Tir', 'Shael', 'Ith']);
days.push(['Dol', 'El', 'Shael', 'Tal', 'Ral', 'Eth', 'Ort', 'Ral', 'Io', 'Hel']);
days.push(['Ort', 'Eth', 'El', 'Ort', 'Ort', 'Sol', 'Tir', 'Mal', 'Ith', 'Ral']);
days.push(['El', 'Amn', 'Ort', 'Amn', 'Tal', 'Ral', 'Thul', 'Eth', 'Io', 'Ko']);
days.push(['Lem', 'Shael', 'Ral', 'Ral', 'Eth', 'Io', 'Tal', 'Ral', 'Ith', 'Eth']);
days.push(['Ral', 'Ral', 'Shael', 'Tal', 'El', 'Ort', 'Tir', 'Tir', 'Tir', 'Shael']);
days.push(['Amn', 'El', 'Io', 'Amn', 'Tal', 'Nef', 'Shael', 'El', 'Hel', 'Hel']);
days.push(['Sol', 'Tal', 'Tal', 'Dol', 'Ith', 'Eth', 'Amn', 'Io', 'Tir', 'Hel']);
days.push(['Ort', 'Nef', 'Ort', 'Ort', 'Tal', 'Eth', 'Ort', 'Tir', 'Tir', 'Tal']);
days.push(['Ort', 'Thul', 'Sol', 'Lum', 'Eth', 'Tal', 'Sol', 'Nef', 'Ort', 'Ort']);
days.push(['Thul', 'Ith', 'Tal', 'Eth', 'Sol', 'Fal', 'Thul', 'Tal', 'Nef', 'Ort']);
days.push(['Ral', 'Ith', 'Ith', 'Amn', 'Ith', 'Thul', 'Amn', 'Eth', 'Io', 'Ral']);
days.push(['Tal', 'Tal', 'Amn', 'Shael', 'Sol', 'Amn', 'Ort', 'Eth', 'Tal', 'Thul']);
days.push(['Ort', 'Ral', 'Shael', 'Shael', 'Amn', 'Ith', 'Eth', 'Tir', 'Nef', 'Tal']);
days.push(['Dol', 'Thul', 'Sol', 'Dol', 'Ort', 'Ort', 'Lum', 'Shael', 'Thul', 'Tal']);
days.push(['Ral', 'Nef', 'Ort', 'Ort', 'Thul', 'Tir', 'Amn', 'Ith', 'Sol', 'Hel']);
days.push(['Eth', 'Thul', 'Ort', 'Sol', 'Eth', 'Ral', 'Thul', 'Ith', 'Ko', 'Eth']);
days.push(['Ith', 'Amn', 'Hel', 'Mal', 'Sol', 'Io', 'Amn', 'Ort', 'Eth', 'Pul']);
days.push(['Tal', 'Amn', 'Tir', 'Tir', 'Ith', 'Sol', 'Ko', 'Sol', 'Amn', 'Shael']);
days.push(['Ral', 'Ort', 'Eth', 'Ort', 'Tal', 'Ort', 'Eth', 'Tal', 'Ith', 'Ral']);
days.push(['Tal', 'Sol', 'Fal', 'Eth', 'Tal', 'Eld', 'Sol', 'Ort', 'Thul', 'Ort']);
days.push(['Eth', 'Dol', 'Thul', 'Amn', 'Tal', 'Ral', 'Eth', 'Eth', 'Amn', 'Ko']);
days.push(['Tal', 'Tir', 'Tal', 'Hel', 'Thul', 'El', 'Shael', 'Thul', 'Thul', 'Eth']);
days.push(['Mal', 'Thul', 'Eth', 'Thul', 'Ith', 'Ort', 'Eth', 'Thul', 'Ort', 'Fal']);
days.push(['Pul', 'Gul', 'Thul', 'Ort', 'Shael', 'Ort', 'Ort', 'Eld', 'Shael', 'Dol']);
days.push(['Shael', 'Ral', 'Eth', 'Hel', 'Tal', 'Tir', 'Ral', 'Thul', 'Amn', 'Ral']);
days.push(['Amn', 'Eth', 'Thul', 'Tir', 'Ort', 'Amn', 'Shael', 'Tal', 'Eth', 'Ort']);
days.push(['Ral', 'Amn', 'Dol', 'Eth', 'Ort', 'Fal', 'Tal', 'Sol', 'Hel', 'Ral']);
days.push(['Ort', 'Eth', 'Amn', 'Amn', 'Sol', 'Ort', 'Ral', 'Eth', 'Amn', 'Nef']);
days.push(['Tal', 'Nef']);

var num = 10;
var aaaa = shuffle(days.flat());
let httt = '';
for (let i = 0; i < aaaa.length; i++) {
  if (i % num == 0) {
    httt += `days.push([`;
  }
  httt += `'${aaaa[i]}'`;
  if (i % num !== num - 1 && i != aaaa.length - 1) {
    httt += `, `;
  } else {
    httt += `]);\n`;
  }
}
console.log(httt);
