days.push(['Amn', 'Amn', 'Tal', 'Sol', 'Eth', 'El', 'Amn', 'Ort', 'Ort', 'Tal']);
days.push(['Ort', 'Lum', 'Dol', 'Nef', 'Tal', 'Ort', 'Ort', 'Eth', 'Ral', 'El']);
days.push(['El', 'Ort', 'Eth', 'Ral', 'Amn', 'Amn', 'Ith', 'Amn', 'Thul', 'Ort']);
days.push(['Sol', 'Amn', 'El', 'Ral', 'Eth', 'Tir', 'Hel', 'Eld', 'Nef', 'Ort']);
days.push(['Io', 'Ort', 'Amn', 'Sol', 'Ith', 'Dol', 'Tir', 'Ral', 'Dol', 'Tal']);
days.push(['Eth', 'Tir', 'Eth', 'Fal', 'Dol', 'Tir', 'Ort', 'Eth', 'Ort', 'Amn']);
days.push(['Ort', 'Lum', 'Amn', 'Ort', 'Tir', 'Ort', 'Tal', 'Ith', 'Dol', 'Eld']);
days.push(['Eld', 'El', 'Thul', 'Sol', 'Thul', 'Amn', 'Mal', 'Hel', 'Nef', 'Tal']);
days.push(['Tal', 'Eth', 'Amn', 'Ort', 'Lum', 'Ort', 'Sol', 'Ort', 'Nef', 'Ith']);
days.push(['Ort', 'Ith', 'Sol', 'Eth', 'El', 'Ith', 'Ith', 'Ort', 'Ort', 'Ort']);
days.push(['Amn', 'Ith', 'Dol', 'Fal', 'Sol', 'Ral', 'El', 'Amn', 'Thul', 'Thul']);
days.push(['Shael', 'Ith', 'Tal', 'Ko', 'Ort', 'Ral', 'Shael', 'Tir', 'Ral', 'Thul']);
days.push(['Ral', 'Eth', 'Nef', 'Ral', 'Ort', 'Ort', 'Tal', 'Shael', 'Eth', 'Eth']);
days.push(['El', 'Amn', 'Eth', 'Thul', 'Eth', 'Ith', 'Ort', 'Sol', 'Eth', 'Ith']);
days.push(['Ort', 'Amn', 'Ort', 'Tal', 'Amn', 'Hel', 'Shael', 'Ral', 'Shael', 'Ort']);
days.push(['Eth', 'Thul', 'Pul', 'Ort', 'Eld', 'Io', 'Nef', 'Io', 'Thul', 'Eld']);
days.push(['Amn', 'Eth', 'Ort', 'Ko', 'Thul', 'Dol', 'Eth', 'Sol', 'Amn', 'Nef']);
days.push(['Dol', 'Eth', 'Ort', 'Eth', 'Hel', 'Eth', 'Sol', 'Amn', 'Tal', 'Ort']);
days.push(['Amn', 'Ort', 'Tir', 'Tal', 'Nef', 'Lem', 'Sol', 'Ral', 'Tal', 'Amn']);
days.push(['Eld', 'Amn', 'Eth', 'Ko', 'Tir', 'Ral', 'Amn', 'Ort', 'Ral', 'Tal']);
days.push(['Eth', 'Tal', 'Ith', 'Ort', 'Eth', 'Thul', 'Ort', 'Sol', 'Tal', 'Dol']);
days.push(['Ort', 'Ko', 'Dol', 'Shael', 'Tal', 'Thul', 'Ith', 'Ort', 'Hel', 'Amn']);
days.push(['Ral', 'Amn', 'Tal', 'Ort', 'Amn', 'Ith', 'Ral', 'Eth', 'Nef', 'Tal']);
days.push(['Tir', 'Ort', 'Mal', 'Shael', 'Amn', 'Ort', 'Tir', 'Lum', 'Tal', 'Eth']);
days.push(['Ral', 'Ral', 'Tal', 'Thul', 'Thul', 'Ort', 'Sol', 'Ral', 'Tir', 'Nef']);
days.push(['Thul', 'Eth', 'Ort', 'Mal', 'Tir', 'Tir', 'Shael', 'Sol', 'Tal', 'Hel']);
days.push(['Amn', 'Shael', 'Tal', 'Eth', 'Ort', 'Thul', 'Thul', 'Tal', 'Mal', 'Ith']);
days.push(['Shael', 'Ort', 'Tal', 'Dol', 'Ith', 'Tal', 'Amn', 'Sol', 'Eth', 'Shael']);
days.push(['Ort', 'Dol', 'Tal', 'Dol', 'Tal', 'Tal', 'Tal', 'Ith', 'Tal', 'Ort']);
days.push(['Nef', 'Sol', 'Amn', 'Tir', 'Shael', 'Tal', 'Eth', 'Nef', 'Eth', 'Thul']);
days.push(['Eth', 'Shael', 'Ort', 'Eth', 'El', 'Amn', 'Dol', 'Tir', 'Tir', 'Shael']);
days.push(['Dol', 'Tal', 'Ral', 'Thul', 'Ral', 'Sol', 'Shael', 'Shael', 'Ort', 'Sol']);
days.push(['Tal', 'Io', 'Ort', 'Amn', 'Ral', 'Dol', 'Amn', 'Sol', 'Eth', 'Amn']);
days.push(['Tal', 'Ko', 'Tir', 'Amn', 'Amn', 'Tal', 'Ort', 'Ort', 'Lum', 'Eth']);
days.push(['Tir', 'Nef', 'Ort', 'Shael', 'Ral', 'Io', 'Ort', 'Dol', 'Sol', 'Hel']);
days.push(['Shael', 'Sol', 'Tal', 'Tal', 'Thul', 'Tir', 'Nef', 'Dol', 'El', 'Amn']);
days.push(['Shael', 'El', 'Nef', 'Ral', 'Amn', 'Ort', 'Tal', 'Sol', 'Ort', 'Thul']);
days.push(['Tal', 'Eth', 'Tal', 'Hel', 'Thul', 'Dol', 'Amn', 'Tal', 'Io', 'Eld']);
days.push(['Eth', 'Shael', 'Eth', 'Ith', 'Amn', 'Eld', 'Ith', 'Tir', 'Amn', 'Tal']);
days.push(['Lum', 'Thul', 'Amn', 'Eth', 'Amn', 'Sol', 'Shael', 'Nef', 'Eth', 'Eth']);
days.push(['Tal', 'Ith', 'Eth', 'Lum', 'Ith', 'Eth', 'Thul', 'Amn', 'Ral', 'Lem']);
days.push(['Tal', 'Tal', 'Hel', 'El', 'Ort', 'Lem', 'Eth', 'Eth', 'El', 'Tal']);
days.push(['Ort', 'Shael', 'Eth', 'Thul', 'Shael', 'Shael', 'Ral', 'Eth', 'Tal', 'Tir']);
days.push(['Tal', 'Tal', 'Ral', 'Amn', 'Shael', 'Ort', 'Lum', 'Ort', 'Ral', 'Ral']);
days.push(['Lum', 'El', 'Nef', 'Dol', 'Sol', 'Io', 'Thul', 'Thul', 'Ral', 'Ral']);
days.push(['Eth', 'Tal', 'Thul', 'Hel', 'Hel', 'Ort', 'El', 'Shael', 'Shael', 'Hel']);
days.push(['Ort', 'Tal', 'Tal', 'Amn', 'El', 'El', 'Tal', 'Ith', 'Pul', 'Ort']);
days.push(['Tal', 'Tir', 'Ith', 'Amn', 'Tal', 'Ort', 'Tal', 'Ort', 'Eth', 'Ith']);
days.push(['Shael', 'Amn', 'Ort', 'Eld', 'Amn', 'Nef', 'Mal', 'Ral', 'Tal', 'Thul']);
days.push(['Ort', 'Nef', 'Amn', 'Ort', 'Thul', 'Gul', 'Ral', 'Ort', 'Amn', 'Tal']);
days.push(['Shael', 'Ral', 'Hel', 'Sol', 'Tal', 'Thul', 'Tal', 'Amn', 'Tir', 'Gul']);
days.push(['Dol', 'Fal', 'Lum', 'Shael', 'Ort', 'Hel', 'Tir', 'Ral', 'Fal', 'Nef']);
days.push(['Tal', 'Tal', 'Um', 'Ko', 'Ort', 'Hel', 'Tal', 'Ort', 'Sol', 'Ort']);
days.push(['Nef', 'Amn', 'Nef', 'El', 'Ort', 'Ort', 'Sol', 'Ral', 'Eth', 'Sol']);
days.push(['Eth', 'Eth', 'Shael', 'Ral', 'Hel', 'Thul', 'Ith', 'Eth', 'Tal', 'Amn']);
days.push(['Shael', 'Tal', 'Tir', 'Thul', 'Fal', 'Thul', 'Tal', 'Amn', 'Io', 'Ort']);
days.push(['Ort', 'Eth', 'Ort', 'Ral', 'Dol', 'Tal', 'Thul', 'Eth', 'Ral', 'Tal']);
days.push(['Shael', 'Io', 'Thul', 'Thul', 'Tal', 'Tal', 'Ith', 'Hel', 'Eth', 'Sol']);
days.push(['Shael', 'Thul', 'Ort', 'Tir', 'Amn', 'Thul', 'Eth', 'Ist', 'Ral', 'Ral']);
days.push(['El', 'Eth', 'Ort', 'Tal', 'Amn', 'Dol', 'Eth', 'Eth', 'Tal', 'Amn']);
days.push(['Ort', 'Eth', 'Tal', 'Ith', 'Thul', 'Amn', 'Tal', 'Amn', 'Ort', 'Hel']);
days.push(['Ort', 'Amn', 'Thul', 'Amn', 'Ral', 'El', 'Amn', 'Sol', 'Dol', 'Shael']);
days.push(['El', 'Shael', 'Tal', 'Ort', 'Ral', 'Thul', 'Shael', 'Ort', 'Shael', 'Hel']);
days.push(['El', 'Thul', 'Tal', 'Ith', 'Amn', 'Thul', 'Eth', 'Shael', 'Tir', 'Tal']);
days.push(['Sol', 'Amn', 'El', 'Ith', 'Tal', 'Ort', 'Tir', 'Dol', 'Dol', 'Ith']);
days.push(['Tal', 'Nef', 'Eth', 'Tir', 'Ort', 'Tal', 'Amn', 'Tal', 'Eld', 'Sol']);
days.push(['Tal', 'Io', 'Sol', 'Tal', 'Sol', 'Ral', 'Hel', 'Um', 'Tir', 'Sol']);
days.push(['Ort', 'Hel', 'Tal', 'Ort', 'Dol', 'Eth', 'Lem', 'Ort', 'Ith', 'Thul']);
days.push(['Hel', 'Shael', 'Tal', 'Tal', 'Thul', 'Ral', 'Eth', 'Tir', 'Sol', 'Eth']);
days.push(['Ort', 'Shael', 'Ort', 'Eth', 'Ko', 'Fal', 'Hel', 'Ort', 'Ral', 'Amn']);
days.push(['Tal', 'Tal', 'Shael', 'Tal', 'Hel', 'Tir', 'Tal', 'Hel', 'Ort', 'Tal']);
days.push(['Nef', 'Ith', 'Ort', 'Tal', 'Ort', 'Ort', 'Thul', 'Eth', 'Tal', 'Amn']);
days.push(['Ort', 'Sol', 'Amn', 'Amn', 'Hel', 'Eld', 'Ral', 'Sol', 'Io', 'Ort']);
days.push(['Tir', 'Ral', 'Amn', 'Sol', 'Eth', 'Fal', 'Ral', 'Tal', 'Eth', 'Hel']);
days.push(['Nef', 'Amn', 'Shael', 'Ral', 'Eth', 'Tal', 'Eth', 'Hel', 'Thul', 'Tir']);
days.push(['Tir', 'Thul', 'Tal', 'Lem', 'Ith', 'Eth', 'Nef', 'Sol', 'Amn', 'Ort']);
days.push(['Shael', 'Tal', 'Tal', 'Ort', 'Nef', 'Ith', 'Amn', 'Tal', 'Tal', 'Tir']);
days.push(['Ral', 'Ko', 'Ral', 'Thul', 'Ith', 'El', 'Sol', 'Nef', 'Sol', 'Tal']);
days.push(['Tal', 'Tal', 'Shael', 'Sol', 'Ral', 'Eth', 'Eth', 'Eth', 'Ort', 'Eth']);
days.push(['Ort', 'Eth', 'Amn', 'Ith', 'Pul', 'Ort', 'Hel', 'Thul', 'Thul', 'Amn']);
days.push(['Hel', 'Tal', 'Thul', 'Thul', 'Ral', 'Eth', 'Tir', 'Sol', 'Shael', 'Amn']);
days.push(['El', 'Tal', 'Tir', 'Ral', 'Ort', 'Shael', 'Thul', 'Ral', 'Ort', 'El']);
days.push(['Thul', 'Ith', 'Lum', 'Thul', 'Sol', 'Ith', 'Shael', 'Thul', 'Lum', 'Tir']);
days.push(['Tir', 'Ort', 'Eth', 'Eth', 'Io', 'Tir', 'Amn', 'Ort', 'Shael', 'Thul']);
days.push(['Thul', 'Eth', 'Tir', 'Lum', 'Ith', 'Ral', 'Ort', 'Ral', 'Ral', 'Ral']);
days.push(['Ral', 'Ort', 'Eth', 'Thul', 'Ral', 'Io', 'Dol', 'Tir', 'Tal', 'Ort']);
days.push(['Ral', 'Tal', 'Sol', 'Amn', 'Amn', 'Eld', 'Ort', 'Lum', 'Ort', 'Tal']);
days.push(['Tal', 'Shael', 'Tal', 'Ko', 'Eth', 'Ort', 'Ort', 'Tal', 'Shael', 'Thul']);
days.push(['Tal', 'Ith', 'Dol', 'Sol', 'Amn', 'Tir', 'Thul', 'Fal', 'Hel', 'Amn']);
days.push(['Ort', 'Tal', 'Ral', 'Ith', 'Tal', 'Thul', 'El', 'Eth', 'Tal', 'Amn']);
days.push(['Eld', 'Sol', 'Ort', 'Ral', 'Ith', 'Eth', 'Tir', 'Ral', 'Hel', 'Amn']);
days.push(['Thul', 'Tal', 'Ort', 'Lum', 'Dol', 'Dol', 'Tal', 'Ist', 'Thul', 'Sol']);
days.push(['Amn', 'Shael', 'Ral', 'Tir', 'Tir', 'Ral', 'Ort', 'Lem', 'Amn', 'Ort']);
days.push(['Um', 'Dol', 'Tir', 'Ort', 'Ral', 'Sol', 'Nef', 'Ort', 'Ral', 'Ral']);


var num = 10;
var aaaa = shuffle(days.flat());
let httt = '';
for (let i = 0; i < aaaa.length; i++) {
  if (i % num == 0) {
    httt += `days.push([`;
  }
  httt += `'${aaaa[i]}'`;
  if (i % num !== num - 1 && i != aaaa.length - 1) {
    httt += `, `;
  } else {
    httt += `]);\n`;
  }
}
console.log(httt);
