let arr = [
  'Armageddon Flange Russet Armor',
  'Armageddon Hide Templar Coat',
  'Armageddon Horn Crown',
  'Armageddon Horn Demonhead',
  'Armageddon Mask Antlers',
  'Armageddon Slayer Silver-Edged Axe',
  'Armageddon Thirst Double Axe',
  'Armageddon Thirst Hydra Edge',
  'Beast Badge Pavise',
  'Beast Bite Crowbill',
  'Beast Fang Long Sword',
  'Beast Fist Greater Talons',
  'Beast Goad Poleaxe',
  'Beast Pale Spetum',
  'Beast Quarrel Short Battle Bow',
  'Beast Shank Heavy Boots',
  'Beast Song Falchion',
  'Beast Spike Bastard Sword',
  'Bitter Breaker Barbed Club',
  'Bitter Clasp Heavy Belt',
  'Bitter Clutches Chain Gloves',
  'Bitter Cowl Bone Helm',
  'Bitter Fang Two-Handed Sword',
  'Bitter Fist Heavy Gloves',
  'Bitter Gnash Tomahawk',
  'Bitter Goad Battle Staff',
  'Bitter Hide Scale Mail',
  'Bitter Mallet Cudgel',
  'Bitter Mangler Jagged Star',
  'Bitter Scythe Throwing Axe',
  'Bitter Scythe Tulwar',
  'Bitter Sever Ataghan',
  'Bitter Song Edge Bow',
  'Bitter Song Spiculum',
  'Bitter Spike Kris',
  'Bitter Splitter Truncheon',
  'Bitter Stinger Spider Bow',
  'Bitter Weaver Grand Scepter',
  'Bitter Wrack Lance',
  'Blood Badge Fetish Trophy',
  'Blood Barb Dimensional Blade',
  'Blood Barb Short Spear',
  'Blood Bite Executioner Sword',
  'Blood Brogues Chain Boots',
  'Blood Claw Cestus',
  'Blood Claw Scissors Katar',
  'Blood Edge Gladius',
  'Blood Flight Short Bow',
  'Blood Mallet Battle Hammer',
  'Blood Scythe Broad Sword',
  'Blood Song Falcata',
  'Blood Song Short Battle Bow',
  'Blood Splitter Cudgel',
  'Blood Thirst Dimensional Blade',
  'Blood Whorl Cloudy Sphere',
  'Bone Bar Truncheon',
  'Bone Bite Brandistock',
  'Bone Coat Trellised Armor',
  'Bone Loom Cedar Bow',
  'Bone Mangler Flanged Mace',
  'Bone Mask Full Helm',
  'Bone Needle Reflex Bow',
  'Bone Quill Short War Bow',
  'Bone Star Bone Wand',
  'Bramble Bow Bone Helm',
  'Bramble Coat Breast Plate',
  'Bramble Mangler Gothic Axe',
  'Bramble Nock Chu-ko-nu',
  'Bramble Pale Fuscina',
  'Bramble Razor Battle Dart',
  'Bramble Reaver Tomahawk',
  'Bramble Wing Bone Shield',
  'Brimstone Blow Flanged Mace',
  'Brimstone Branch Brandistock',
  'Brimstone Branch Edge Bow',
  'Brimstone Brow Lion Helm',
  'Brimstone Cloak Splint Mail',
  'Brimstone Crest Winged Helm',
  'Brimstone Hew Blade',
  'Brimstone Horn Repeating Crossbow',
  'Brimstone Loom Heavy Crossbow',
  'Brimstone Nock Short War Bow',
  'Brimstone Quarrel Spider Bow',
  'Brimstone Rend War Axe',
  'Brimstone Song Maiden Pike',
  'Brimstone Stake Bill',
  'Brimstone Stinger Razor Bow',
  'Carrion Barb Great Pilum',
  'Carrion Bolt Simbilan',
  'Carrion Cloak Scarab Husk',
  'Carrion Dart Pike',
  'Carrion Fringe Mithril Coil',
  'Carrion Hew Falchion',
  'Carrion Knell Morning Star',
  'Carrion Mantle Gothic Plate',
  'Carrion Quill Poignard',
  'Carrion Scalpel Kris',
  'Carrion Scalpel Stiletto',
  'Carrion Scythe Throwing Axe',
  'Carrion Shield Large Shield',
  'Carrion Song Reinforced Mace',
  'Carrion Song Two-Handed Sword',
  'Carrion Stake Yari',
  'Carrion Strap Plated Belt',
  'Carrion Thirst Throwing Axe',
  'Carrion Tower Small Shield',
  'Carrion Veil Crown',
  'Carrion Wrap Sharktooth Armor',
  'Corpse Bite Balanced Knife',
  'Corpse Bite Gladius',
  'Corpse Cowl Shako',
  'Corpse Crest Horned Helm',
  'Corpse Emblem Rondache',
  'Corpse Fang Two-Handed Sword',
  'Corpse Impaler Halberd',
  'Corpse Mallet Maul',
  'Corpse Prod Grim Scythe',
  'Corpse Razor Scissors Katar',
  'Corpse Scratch Hyperion Spear',
  'Corpse Scythe Flamberge',
  'Corpse Song Claws',
  'Corpse Spike Poleaxe',
  'Corpse Stake Lochaber Axe',
  'Corpse Suit Breast Plate',
  'Corpse Thirst Blade',
  'Corpse Wood Spetum',
  'Cruel Bane Morning Star',
  'Cruel Clasp Belt',
  'Cruel Emblem Dragon Shield',
  'Cruel Fang Balanced Knife',
  'Cruel Fang Grim Scythe',
  'Cruel Hide Studded Leather',
  'Cruel Impaler Long Sword',
  'Cruel Mangler Martel De Fer',
  'Cruel Pelt Gothic Plate',
  'Cruel Scalpel War Sword',
  'Cruel Shield Scutum',
  'Cruel Skewer Legend Sword',
  'Cruel Star War Hammer',
  'Cruel Ward Grim Shield',
  'Death Bar Mace',
  'Death Bolt Long Battle Bow',
  'Death Branch Hyperion Spear',
  'Death Edge War Axe',
  'Death Goad Bec-de-corbin',
  'Death Grasp Bramble Mitts',
  'Death Guard Targe',
  'Death Gyre Sacred Globe',
  'Death Hide Serpentskin Armor',
  'Death Lance Glaive',
  'Death Scratch Tulwar',
  'Death Shield Protector Shield',
  'Death Shield Zombie Head',
  'Death Song Rune Scepter',
  'Death Spiral Ring',
  'Death Sunder Large Axe',
  'Death Touch Heavy Gloves',
  'Death Wyrmhide Nails Boots',
  'Demon Barb Rune Sword',
  'Demon Bite Battle Axe',
  'Demon Bite Flying Axe',
  'Demon Gutter Dirk',
  'Demon Hew Dimensional Blade',
  'Demon Mangler Balanced Axe',
  'Demon Mangler Feral Axe',
  'Demon Nails Lance',
  'Demon Scratch Brandistock',
  'Demon Shell Full Helm',
  'Demon Slayer Double Axe',
  'Demon Spell Lich Wand',
  'Demon Tread Sharkskin Boots',
  'Demon Visor Bone Helm',
  'Demon Ward Aerin Shield',
  'Dire Bite Claws',
  'Dire Cowl Rage Mask',
  'Dire Mask Sallet',
  'Dire Needle Throwing Spear',
  'Dire Scythe Shamshir',
  'Dire Spike Tulwar',
  'Dire Star Reinforced Mace',
  'Dire Stinger Spider Bow',
  'Dire Sunder Twin Axe',
  'Dire Thirst Spear',
  'Doom Bite Cestus',
  'Doom Bite Claymore',
  'Doom Claw Claws',
  'Doom Cleaver Feral Axe',
  'Doom Cowl Sallet',
  'Doom Crusher Battle Hammer',
  'Doom Dart War Spear',
  'Doom Fang Hydra Edge',
  'Doom Gnarl Gnarled Staff',
  'Doom Harness Belt',
  'Doom Lance Poleaxe',
  'Doom Quarrel Short Siege Bow',
  'Doom Rock Luna',
  'Doom Song Long Battle Bow',
  'Doom Stinger Bone Knife',
  'Doom Thirst Throwing Axe',
  'Doom Ward Heater',
  'Dread Cloak Russet Armor',
  'Dread Flange Splint Mail',
  'Dread Flange Wire Fleece',
  'Dread Fletch Gothic Bow',
  'Dread Grasp Chain Gloves',
  'Dread Horn Circlet',
  'Dread Mangler Throwing Axe',
  'Dread Needle Bone Knife',
  'Dread Razor Bearded Axe',
  'Dread Rock Kite Shield',
  'Dread Scythe Silver-Edged Axe',
  'Dread Shell Ancient Armor',
  'Dread Whorl Clasped Orb',
  'Eagle Band Ring',
  'Eagle Bite Grim Scythe',
  'Eagle Bolt Spiculum',
  'Eagle Chant War Staff',
  'Eagle Cowl Winged Helm',
  'Eagle Edge Falchion',
  'Eagle Flight Hyperion Javelin',
  'Eagle Hood Shako',
  'Eagle Lock Plated Belt',
  'Eagle Pelt Russet Armor',
  'Eagle Rock Bone Shield',
  'Eagle Scarab Amulet',
  'Eagle Splitter Twin Axe',
  'Eagle Stinger Long War Bow',
  'Eagle Thirst Dirk',
  'Eagle Thirst Hydra Edge',
  'Eagle Thirst Partizan',
  'Eagle Wood Short Spear',
  'Empyrian Cry Grave Wand',
  'Entropy Clasp Amulet',
  'Fiend Aegis Round Shield',
  'Fiend Dart Diamond Bow',
  'Fiend Emblem Scutum',
  'Fiend Fletch Diamond Bow',
  'Fiend Flight Short Bow',
  'Fiend Grip Gauntlets',
  'Fiend Gyre Crystalline Globe',
  'Fiend Horn Short Siege Bow',
  'Fiend Mantle Plate Mail',
  'Fiend Mask Hunter`s Guise',
  'Fiend Pelt Demonhide Armor',
  'Fiend Pelt Great Hauberk',
  'Fiend Rock Scutum',
  'Fiend Thirst Zweihander',
  'Fiend Wrack Harpoon',
  'Gale Barb Pike',
  'Gale Bite Poleaxe',
  'Gale Bludgeon Mace',
  'Gale Crest Antlers',
  'Gale Edge Legend Sword',
  'Gale Fang Yari',
  'Gale Harp Arbalest',
  'Gale Nails Glaive',
  'Gale Needle Brandistock',
  'Gale Quarrel Rune Bow',
  'Gale Rock Gargoyle Head',
  'Gale Scythe War Scythe',
  'Gale Skewer Battle Dart',
  'Gale Skewer Winged Harpoon',
  'Gale Spell Long Staff',
  'Gale Stalker Greaves',
  'Gale Trample Mirrored Boots',
  'Gale Visage Jawbone Cap',
  'Gale Visage Shako',
  'Gale Winding Mithril Coil',
  'Ghoul Branch Razor Bow',
  'Ghoul Crest Death Mask',
  'Ghoul Gnash War Club',
  'Ghoul Gorget Amulet',
  'Ghoul Hide Chain Mail',
  'Ghoul Pale Spetum',
  'Ghoul Scourge Spetum',
  'Ghoul Scratch Halberd',
  'Ghoul Shield Sacred Rondache',
  'Ghoul Song Long Bow',
  'Ghoul Splitter Axe',
  'Ghoul Thirst Balanced Knife',
  'Ghoul Veil Great Helm',
  'Ghoul Ward Sexton Trophy',
  'Ghoul Wing Defender',
  'Glyph Chain Belt',
  'Glyph Crack War Hammer',
  'Glyph Horn Spirit Mask',
  'Glyph Horn Wolf Head',
  'Glyph Jack Chain Mail',
  'Glyph Knuckle Gauntlets',
  'Glyph Rend Double Axe',
  'Glyph Scratch Falcata',
  'Glyph Slayer Military Axe',
  'Glyph Suit Chain Mail',
  'Grim Aegis Pavise',
  'Grim Bar Jagged Star',
  'Grim Dart Pilum',
  'Grim Flange Splint Mail',
  'Grim Heart Smoked Sphere',
  'Grim Mar Battle Sword',
  'Grim Mar Cudgel',
  'Grim Mask Grand Crown',
  'Grim Quarrel Repeating Crossbow',
  'Grim Saw Gladius',
  'Grim Scythe Cleaver',
  'Grim Slayer Military Axe',
  'Grim Song Blade Bow',
  'Grim Song Stiletto',
  'Grim Spike War Spear',
  'Grim Spiral Ring',
  'Grim Splitter Ancient Axe',
  'Grim Wrap Linked Mail',
  'Hailstone Bar Short Spear',
  'Hailstone Barb Cinquedeas',
  'Hailstone Chant War Scepter',
  'Hailstone Crest Horned Helm',
  'Hailstone Flange Plate Mail',
  'Hailstone Hew Axe',
  'Hailstone Horn Repeating Crossbow',
  'Hailstone Knell Mace',
  'Hailstone Lum Eagle Bow',
  'Hailstone Needle Edge Bow',
  'Hailstone Pale Poleaxe',
  'Hailstone Razor Flamberge',
  'Hailstone Shell Kite Shield',
  'Hailstone Spawn Throwing Axe',
  'Hailstone Veil Lion Helm',
  'Hailstone Visage Circlet',
  'Havoc Aegis Bone Shield',
  'Havoc Barb Hyperion Spear',
  'Havoc Bite Dirk',
  'Havoc Claw Light Gauntlets',
  'Havoc Coat Chain Mail',
  'Havoc Cowl Lion Helm',
  'Havoc Crack Maul',
  'Havoc Crusher Scourge',
  'Havoc Grasp Gauntlets',
  'Havoc Loom Long War Bow',
  'Havoc Needle Rune Bow',
  'Havoc Saw Broad Sword',
  'Havoc Sever Axe',
  'Havoc Skewer Glaive',
  'Havoc Splitter Giant Axe',
  'Havoc Thirst Throwing Spear',
  'Imp Bar Long Staff',
  'Imp Branch Elder Staff',
  'Imp Coat Diamond Mail',
  'Imp Emblem Unraveller Head',
  'Imp Fang Battle Dart',
  'Imp Fist Bramble Mitts',
  'Imp Fist Claws',
  'Imp Fletch Gothic Bow',
  'Imp Gnarl Long Staff',
  'Imp Greaves Greaves',
  'Imp Gyre Clasped Orb',
  'Imp Hand Heavy Bracers',
  'Imp Lance War Fork',
  'Imp Mangler Twin Axe',
  'Imp Mar Balanced Knife',
  'Imp Nock Ceremonial Bow',
  'Imp Razor Scissors Quhab',
  'Imp Shield Unraveller Head',
  'Imp Song Clasped Orb',
  'Imp Star Mighty Scepter',
  'Imp Thirst War Dart',
  'Loath Bite Hurlbat',
  'Loath Emblem Spiked Shield',
  'Loath Guard Defender',
  'Loath Mask Death Mask',
  'Loath Scratch Bone Knife',
  'Loath Song Gnarled Staff',
  'Loath Song Tyrant Club',
  'Loath Stinger Gothic Bow',
  'Loath Stinger Stygian Pike',
  'Loath Visor Winged Helm',
  'Loath Winding Plated Belt',
  'Order Beads Amulet',
  'Order Scarab Amulet',
  'Pain Bar Poleaxe',
  'Pain Casque Mask',
  'Pain Circlet Grand Conch',
  'Pain Cloak Gothic Plate',
  'Pain Gnash Crowbill',
  'Pain Grasp Bramble Mitts',
  'Pain Gutter Highland Blade',
  'Pain Harp Short War Bow',
  'Pain Hew Espandon',
  'Pain Knuckle Bramble Mitts',
  'Pain Knuckle Bramble Mitts',
  'Pain Mangler Battle Axe',
  'Pain Mar Great Maul',
  'Pain Quill Long Battle Bow',
  'Pain Saw Falchion',
  'Pain Scythe Naga',
  'Pain Skewer Phase Blade',
  'Pain Song Twin Axe',
  'Pain Star Grand Scepter',
  'Pain Thirst Military Pick',
  'Plague Branch Great Bow',
  'Plague Cudgel Barbed Club',
  'Plague Edge Poignard',
  'Plague Fang Legend Sword',
  'Plague Hide Breast Plate',
  'Plague Jack Chaos Armor',
  'Plague Knell War Scepter',
  'Plague Knuckle Bramble Mitts',
  'Plague Mantle Full Plate Mail',
  'Plague Nails Fuscina',
  'Plague Quarrel Reflex Bow',
  'Plague Saw Great Sword',
  'Plague Scourge Hyperion Spear',
  'Plague Shell Antlers',
  'Plague Splitter War Hammer',
  'Plague Stinger Short War Bow',
  'Plague Thirst Greater Talons',
  'Plague Veil Circlet',
  'Raven Bite Small Crescent',
  'Raven Bolt Shadow Bow',
  'Raven Hide Scale Mail',
  'Raven Mallet Tyrant Club',
  'Raven Picket War Scythe',
  'Raven Quill Reflex Bow',
  'Raven Thirst Kris',
  'Raven Thirst Tomahawk',
  'Raven Wood Bec-de-Corbin',
  'Rune Bar Short Spear',
  'Rune Carapace Breast Plate',
  'Rune Grasp Ring',
  'Rune Scythe Double Axe',
  'Rune Song Fascia',
  'Rune Stake Maiden Pike',
  'Rune Whorl Sacred Globe',
  'Shadow Bar Flail',
  'Shadow Bolt Double Bow',
  'Shadow Brand War Staff',
  'Shadow Clasp Demonhide Sash',
  'Shadow Crack Jagged Star',
  'Shadow Hew Sabre',
  'Shadow Hood Tiara',
  'Shadow Hook Crown',
  'Shadow Horn Cedar Bow',
  'Shadow Mantle Linked Mail',
  'Shadow Mark Spiked Shield',
  'Shadow Needle Composite Bow',
  'Shadow Pelt Chain Mail',
  'Shadow Razor Blade Talons',
  'Shadow Rend Axe',
  'Shadow Shield Unraveller Head',
  'Shadow Slayer Hurlbat',
  'Shadow Thirst Short Spear',
  'Shadow Veil Shako',
  'Shadow Wrap Field Plate',
  'Skull Barb Gladius',
  'Skull Cloak Great Hauberk',
  'Skull Flange Scale Mail',
  'Skull Grasp Demonhide Gloves',
  'Skull Rock Heraldic Shield',
  'Skull Scourge Spetum',
  'Skull Scratch Claws',
  'Skull Scratch Poignard',
  'Skull Shell Crown',
  'Skull Stake Brandistock',
  'Skull Stinger Hyperion Spear',
  'Skull Thirst Scissors Katar',
  'Skull Tower Demon Head',
  'Soul Barb Poleaxe',
  'Soul Casque Full Helm',
  'Soul Claw Hatchet Hands',
  'Soul Crack Flail',
  'Soul Gutter Glaive',
  'Soul Mask Skull Cap',
  'Soul Needle Winged Knife',
  'Soul Razor Kris',
  'Soul Shell Chain Mail',
  'Soul Shield Dragon Shield',
  'Soul Spike Dacian Falx',
  'Soul Stake Hyperion Javelin',
  'Spirit Coat Breast Plate',
  'Spirit Fringe Light Belt',
  'Spirit Jack Breast Plate',
  'Spirit Pelt Breast Plate',
  'Spirit Touch Battle Gauntlets',
  'Stone Bane Tomb Wand',
  'Stone Bite Scimitar',
  'Stone Fist Quhab',
  'Stone Flight Pilum',
  'Stone Hand Chain Gloves',
  'Stone Hood Crown',
  'Stone Horn Hunter`s Bow',
  'Stone Horn Short War Bow',
  'Stone Scratch Hatchet Hands',
  'Stone Song Flail',
  'Stone Thirst Crystal Sword',
  'Storm Aegis Defender',
  'Storm Bite Giant Axe',
  'Storm Bite Spetum',
  'Storm Collar Amulet',
  'Storm Emblem Unraveller Head',
  'Storm Fist Scissors Katar',
  'Storm Fletch Heavy Crossbow',
  'Storm Greaves Greaves',
  'Storm Gyre Clasped Orb',
  'Storm Gyre Jared`s Stone',
  'Storm Hew War Dart',
  'Storm Mangler Balanced Axe',
  'Storm Mangler Tyrant Club',
  'Storm Mantle Mage Plate',
  'Storm Mar Stygian Pilum',
  'Storm Needle Claymore',
  'Storm Pelt Serpentskin Armor',
  'Storm Prod Pilum',
  'Storm Quarrel Long Bow',
  'Storm Razor Kris',
  'Storm Razor Wrist Blade',
  'Storm Rend Battle Axe',
  'Storm Rend Double Axe',
  'Storm Rock Bone Shield',
  'Storm Scratch Bardiche',
  'Storm Sever Military Pick',
  'Storm Shroud Demonhide Armor',
  'Storm Skewer Giant Sword',
  'Storm Song Ancient Sword',
  'Storm Song Balanced Knife',
  'Storm Stinger Dacian Falx',
  'Storm Thirst Decapitator',
  'Storm Veil Tiara',
  'Storm Whorl Heavenly Stone',
  'Storm Wrack Hyperion Javelin',
  'Viper Bite War Sword',
  'Viper Breaker Martel De Fer',
  'Viper Fist Wrist Blade',
  'Viper Grinder Cudgel',
  'Viper Hide Studded Leather',
  'Viper Horn Alpha Helm',
  'Viper Impaler Dimensional Blade',
  'Viper Pelt Dusk Shroud',
  'Viper Scourge War Javelin',
  'Viper Song War Fist',
  'Viper Stalker Wyrmhide Boots',
  'Viper Star Martel De Fer',
  'Viper Veil Sacred Feathers',
  'Wraith Carapace Ornate Plate',
  'Wraith Coat Wyrmhide',
  'Wraith Flight Crossbow',
  'Wraith Scalpel Crystal Sword',
  'Wraith Spike Short Spear',
  'Wraith Ward Grim Shield',
];

console.log(arr.sort());
