let arr = [
  'Armageddon Flange Russet Armor',
  'Armageddon Hide Templar Coat',
  'Armageddon Horn Crown',
  'Armageddon Horn Demonhead',
  'Armageddon Mask Antlers',
  'Armageddon Slayer Silver-Edged Axe',
  'Armageddon Thirst Double Axe',
  'Armageddon Thirst Hydra Edge',
  'Beast Badge Pavise',
  'Beast Bite Crowbill',
  'Beast Fang Long Sword',
  'Beast Fist Greater Talons',
  'Beast Goad Poleaxe',
  'Beast Pale Spetum',
  'Beast Quarrel Short Battle Bow',
  'Beast Shank Heavy Boots',
  'Beast Song Falchion',
  'Beast Spike Bastard Sword',
  'Bitter Breaker Barbed Club',
  'Bitter Clasp Heavy Belt',
  'Bitter Clutches Chain Gloves',
  'Bitter Cowl Bone Helm',
  'Bitter Fang Two-Handed Sword',
  'Bitter Fist Heavy Gloves',
  'Bitter Gnash Tomahawk',
  'Bitter Goad Battle Staff',
  'Bitter Mallet Cudgel',
  'Bitter Scythe Throwing Axe',
  'Bitter Scythe Tulwar',
  'Bitter Sever Ataghan',
  'Bitter Song Edge Bow',
  'Bitter Song Spiculum',
  'Bitter Spike Kris',
  'Bitter Splitter Truncheon',
  'Bitter Weaver Grand Scepter',
  'Bitter Wrack Lance',
  'Blood Badge Fetish Trophy',
  'Blood Barb Dimensional Blade',
  'Blood Barb Short Spear',
  'Blood Bite Executioner Sword',
  'Blood Brogues Chain Boots',
  'Blood Claw Cestus',
  'Blood Claw Scissors Katar',
  'Blood Edge Gladius',
  'Blood Flight Short Bow',
  'Blood Mallet Battle Hammer',
  'Blood Song Falcata',
  'Blood Song Short Battle Bow',
  'Bone Bar Truncheon',
  'Bone Bite Brandistock',
  'Bone Coat Trellised Armor',
  'Bone Loom Cedar Bow',
  'Bone Mask Full Helm',
  'Bone Needle Reflex Bow',
  'Bone Quill Short War Bow',
  'Bone Star Bone Wand',
  'Bramble Coat Breast Plate',
  'Bramble Mangler Gothic Axe',
  'Bramble Nock Chu-ko-nu',
  'Bramble Pale Fuscina',
  'Bramble Reaver Tomahawk',
  'Bramble Wing Bone Shield',
  'Brimstone Branch Brandistock',
  'Brimstone Branch Edge Bow',
  'Brimstone Cloak Splint Mail',
  'Brimstone Crest Winged Helm',
  'Brimstone Hew Blade',
  'Brimstone Horn Repeating Crossbow',
  'Brimstone Loom Heavy Crossbow',
  'Brimstone Nock Short War Bow',
  'Brimstone Rend War Axe',
  'Brimstone Song Maiden Pike',
  'Brimstone Stinger Razor Bow',
  'Carrion Barb Great Pilum',
  'Carrion Bolt Simbilan',
  'Carrion Cloak Scarab Husk',
  'Carrion Fringe Mithril Coil',
  'Carrion Hew Falchion',
  'Carrion Knell Morning Star',
  'Carrion Mantle Gothic Plate',
  'Carrion Quill Poignard',
  'Carrion Scalpel Kris',
  'Carrion Scalpel Stiletto',
  'Carrion Scythe Throwing Axe',
  'Carrion Shield Large Shield',
  'Carrion Song Reinforced Mace',
  'Carrion Song Two-Handed Sword',
  'Carrion Stake Yari',
  'Carrion Strap Plated Belt',
  'Carrion Thirst Throwing Axe',
  'Carrion Veil Crown',
  'Carrion Wrap Sharktooth Armor',
  'Corpse Bite Gladius',
  'Corpse Cowl Shako',
  'Corpse Crest Horned Helm',
  'Corpse Emblem Rondache',
  'Corpse Fang Two-Handed Sword',
  'Corpse Impaler Halberd',
  'Corpse Razor Scissors Katar',
  'Corpse Scratch Hyperion Spear',
  'Corpse Scythe Flamberge',
  'Corpse Song Claws',
  'Corpse Spike Poleaxe',
  'Corpse Stake Lochaber Axe',
  'Corpse Suit Breast Plate',
  'Corpse Thirst Blade',
  'Corpse Wood Spetum',
  'Cruel Clasp Belt',
  'Cruel Emblem Dragon Shield',
  'Cruel Fang Grim Scythe',
  'Cruel Hide Studded Leather',
  'Cruel Impaler Long Sword',
  'Cruel Mangler Martel De Fer',
  'Cruel Pelt Gothic Plate',
  'Cruel Scalpel War Sword',
  'Cruel Shield Scutum',
  'Cruel Skewer Legend Sword',
  'Cruel Star War Hammer',
  'Cruel Ward Grim Shield',
  'Death Bolt Long Battle Bow',
  'Death Branch Hyperion Spear',
  'Death Edge War Axe',
  'Death Goad Bec-de-corbin',
  'Death Grasp Bramble Mitts',
  'Death Guard Targe',
  'Death Gyre Sacred Globe',
  'Death Hide Serpentskin Armor',
  'Death Lance Glaive',
  'Death Scratch Tulwar',
  'Death Shield Zombie Head',
  'Death Song Rune Scepter',
  'Death Touch Heavy Gloves',
  'Death Wyrmhide Nails Boots',
  'Demon Bite Battle Axe',
  'Demon Bite Flying Axe',
  'Demon Gutter Dirk',
  'Demon Hew Dimensional Blade',
  'Demon Mangler Feral Axe',
  'Demon Scratch Brandistock',
  'Demon Shell Full Helm',
  'Demon Slayer Double Axe',
  'Demon Spell Lich Wand',
  'Demon Visor Bone Helm',
  'Dire Cowl Rage Mask',
  'Dire Mask Sallet',
  'Dire Needle Throwing Spear',
  'Dire Scythe Shamshir',
  'Dire Spike Tulwar',
  'Dire Star Reinforced Mace',
  'Dire Stinger Spider Bow',
  'Dire Sunder Twin Axe',
  'Doom Bite Cestus',
  'Doom Bite Claymore',
  'Doom Claw Claws',
  'Doom Cleaver Feral Axe',
  'Doom Cowl Sallet',
  'Doom Crusher Battle Hammer',
  'Doom Dart War Spear',
  'Doom Fang Hydra Edge',
  'Doom Gnarl Gnarled Staff',
  'Doom Harness Belt',
  'Doom Lance Poleaxe',
  'Doom Rock Luna',
  'Doom Stinger Bone Knife',
  'Doom Thirst Throwing Axe',
  'Doom Ward Heater',
  'Dread Cloak Russet Armor',
  'Dread Flange Wire Fleece',
  'Dread Fletch Gothic Bow',
  'Dread Grasp Chain Gloves',
  'Dread Horn Circlet',
  'Dread Needle Bone Knife',
  'Dread Razor Bearded Axe',
  'Dread Scythe Silver-Edged Axe',
  'Dread Shell Ancient Armor',
  'Dread Whorl Clasped Orb',
  'Eagle Bite Grim Scythe',
  'Eagle Bolt Spiculum',
  'Eagle Chant War Staff',
  'Eagle Cowl Winged Helm',
  'Eagle Edge Falchion',
  'Eagle Flight Hyperion Javelin',
  'Eagle Hood Shako',
  'Eagle Pelt Russet Armor',
  'Eagle Stinger Long War Bow',
  'Eagle Thirst Hydra Edge',
  'Eagle Thirst Partizan',
  'Eagle Wood Short Spear',
  'Empyrian Cry Grave Wand',
  'Fiend Aegis Round Shield',
  'Fiend Dart Diamond Bow',
  'Fiend Emblem Scutum',
  'Fiend Fletch Diamond Bow',
  'Fiend Gyre Crystalline Globe',
  'Fiend Horn Short Siege Bow',
  'Fiend Mantle Plate Mail',
  'Fiend Mask Hunter`s Guise',
  'Fiend Pelt Demonhide Armor',
  'Fiend Pelt Great Hauberk',
  'Fiend Rock Scutum',
  'Fiend Thirst Zweihander',
  'Fiend Wrack Harpoon',
  'Gale Barb Pike',
  'Gale Bludgeon Mace',
  'Gale Crest Antlers',
  'Gale Edge Legend Sword',
  'Gale Fang Yari',
  'Gale Harp Arbalest',
  'Gale Nails Glaive',
  'Gale Needle Brandistock',
  'Gale Quarrel Rune Bow',
  'Gale Scythe War Scythe',
  'Gale Skewer Battle Dart',
  'Gale Skewer Winged Harpoon',
  'Gale Spell Long Staff',
  'Gale Stalker Greaves',
  'Gale Visage Shako',
  'Gale Winding Mithril Coil',
  'Ghoul Gnash War Club',
  'Ghoul Hide Chain Mail',
  'Ghoul Pale Spetum',
  'Ghoul Scratch Halberd',
  'Ghoul Shield Sacred Rondache',
  'Ghoul Veil Great Helm',
  'Ghoul Ward Sexton Trophy',
  'Ghoul Wing Defender',
  'Glyph Crack War Hammer',
  'Glyph Horn Wolf Head',
  'Glyph Knuckle Gauntlets',
  'Glyph Rend Double Axe',
  'Glyph Scratch Falcata',
  'Glyph Slayer Military Axe',
  'Grim Aegis Pavise',
  'Grim Dart Pilum',
  'Grim Flange Splint Mail',
  'Grim Mar Battle Sword',
  'Grim Mar Cudgel',
  'Grim Mask Grand Crown',
  'Grim Scythe Cleaver',
  'Grim Song Blade Bow',
  'Grim Song Stiletto',
  'Grim Spike War Spear',
  'Grim Splitter Ancient Axe',
  'Grim Wrap Linked Mail',
  'Hailstone Barb Cinquedeas',
  'Hailstone Chant War Scepter',
  'Hailstone Crest Horned Helm',
  'Hailstone Flange Plate Mail',
  'Hailstone Hew Axe',
  'Hailstone Horn Repeating Crossbow',
  'Hailstone Knell Mace',
  'Hailstone Lum Eagle Bow',
  'Hailstone Needle Edge Bow',
  'Hailstone Pale Poleaxe',
  'Hailstone Razor Flamberge',
  'Hailstone Shell Kite Shield',
  'Havoc Aegis Bone Shield',
  'Havoc Barb Hyperion Spear',
  'Havoc Bite Dirk',
  'Havoc Claw Light Gauntlets',
  'Havoc Coat Chain Mail',
  'Havoc Cowl Lion Helm',
  'Havoc Crack Maul',
  'Havoc Crusher Scourge',
  'Havoc Grasp Gauntlets',
  'Havoc Loom Long War Bow',
  'Havoc Saw Broad Sword',
  'Havoc Sever Axe',
  'Havoc Splitter Giant Axe',
  'Havoc Thirst Throwing Spear',
  'Imp Coat Diamond Mail',
  'Imp Emblem Unraveller Head',
  'Imp Fang Battle Dart',
  'Imp Fist Bramble Mitts',
  'Imp Fist Claws',
  'Imp Fletch Gothic Bow',
  'Imp Gnarl Long Staff',
  'Imp Greaves Greaves',
  'Imp Hand Heavy Bracers',
  'Imp Mangler Twin Axe',
  'Imp Mar Balanced Knife',
  'Imp Nock Ceremonial Bow',
  'Imp Star Mighty Scepter',
  'Imp Thirst War Dart',
  'Loath Guard Defender',
  'Loath Mask Death Mask',
  'Loath Scratch Bone Knife',
  'Loath Song Gnarled Staff',
  'Loath Song Tyrant Club',
  'Loath Stinger Gothic Bow',
  'Loath Winding Plated Belt',
  'Pain Casque Mask',
  'Pain Circlet Grand Conch',
  'Pain Cloak Gothic Plate',
  'Pain Gnash Crowbill',
  'Pain Gutter Highland Blade',
  'Pain Harp Short War Bow',
  'Pain Knuckle Bramble Mitts',
  'Pain Knuckle Bramble Mitts',
  'Pain Mar Great Maul',
  'Pain Quill Long Battle Bow',
  'Pain Scythe Naga',
  'Pain Skewer Phase Blade',
  'Pain Thirst Military Pick',
  'Plague Branch Great Bow',
  'Plague Cudgel Barbed Club',
  'Plague Fang Legend Sword',
  'Plague Hide Breast Plate',
  'Plague Knell War Scepter',
  'Plague Knuckle Bramble Mitts',
  'Plague Nails Fuscina',
  'Plague Quarrel Reflex Bow',
  'Plague Saw Great Sword',
  'Plague Scourge Hyperion Spear',
  'Plague Shell Antlers',
  'Plague Splitter War Hammer',
  'Plague Stinger Short War Bow',
  'Plague Veil Circlet',
  'Raven Bite Small Crescent',
  'Raven Bolt Shadow Bow',
  'Raven Hide Scale Mail',
  'Raven Picket War Scythe',
  'Raven Thirst Kris',
  'Raven Thirst Tomahawk',
  'Rune Bar Short Spear',
  'Rune Song Fascia',
  'Rune Stake Maiden Pike',
  'Shadow Bar Flail',
  'Shadow Bolt Double Bow',
  'Shadow Brand War Staff',
  'Shadow Clasp Demonhide Sash',
  'Shadow Crack Jagged Star',
  'Shadow Hood Tiara',
  'Shadow Hook Crown',
  'Shadow Horn Cedar Bow',
  'Shadow Mantle Linked Mail',
  'Shadow Mark Spiked Shield',
  'Shadow Needle Composite Bow',
  'Shadow Razor Blade Talons',
  'Shadow Rend Axe',
  'Shadow Slayer Hurlbat',
  'Shadow Veil Shako',
  'Shadow Wrap Field Plate',
  'Skull Barb Gladius',
  'Skull Cloak Great Hauberk',
  'Skull Grasp Demonhide Gloves',
  'Skull Rock Heraldic Shield',
  'Skull Scourge Spetum',
  'Skull Scratch Claws',
  'Skull Scratch Poignard',
  'Skull Shell Crown',
  'Skull Stake Brandistock',
  'Skull Stinger Hyperion Spear',
  'Skull Tower Demon Head',
  'Soul Casque Full Helm',
  'Soul Claw Hatchet Hands',
  'Soul Crack Flail',
  'Soul Gutter Glaive',
  'Soul Needle Winged Knife',
  'Soul Razor Kris',
  'Soul Shell Chain Mail',
  'Soul Stake Hyperion Javelin',
  'Spirit Coat Breast Plate',
  'Spirit Fringe Light Belt',
  'Spirit Jack Breast Plate',
  'Stone Bane Tomb Wand',
  'Stone Flight Pilum',
  'Stone Hand Chain Gloves',
  'Stone Hood Crown',
  'Stone Horn Hunter`s Bow',
  'Stone Horn Short War Bow',
  'Stone Scratch Hatchet Hands',
  'Stone Thirst Crystal Sword',
  'Storm Aegis Defender',
  'Storm Bite Spetum',
  'Storm Fist Scissors Katar',
  'Storm Hew War Dart',
  'Storm Mangler Balanced Axe',
  'Storm Mangler Tyrant Club',
  'Storm Mantle Mage Plate',
  'Storm Mar Stygian Pilum',
  'Storm Needle Claymore',
  'Storm Pelt Serpentskin Armor',
  'Storm Prod Pilum',
  'Storm Quarrel Long Bow',
  'Storm Razor Kris',
  'Storm Razor Wrist Blade',
  'Storm Rend Battle Axe',
  'Storm Rend Double Axe',
  'Storm Rock Bone Shield',
  'Storm Scratch Bardiche',
  'Storm Sever Military Pick',
  'Storm Shroud Demonhide Armor',
  'Storm Skewer Giant Sword',
  'Storm Song Ancient Sword',
  'Storm Stinger Dacian Falx',
  'Storm Thirst Decapitator',
  'Storm Veil Tiara',
  'Viper Bite War Sword',
  'Viper Fist Wrist Blade',
  'Viper Grinder Cudgel',
  'Viper Hide Studded Leather',
  'Viper Horn Alpha Helm',
  'Viper Impaler Dimensional Blade',
  'Viper Pelt Dusk Shroud',
  'Viper Scourge War Javelin',
  'Viper Song War Fist',
  'Viper Stalker Wyrmhide Boots',
  'Wraith Carapace Ornate Plate',
  'Wraith Coat Wyrmhide',
  'Wraith Scalpel Crystal Sword',
  'Wraith Spike Short Spear',
  'Wraith Ward Grim Shield',
];

console.log(arr.sort());
