let arr =
  ('Armageddon Horn Crown',
  'Armageddon Slayer Silver-Edged Axe',
  'Beast Badge Pavise',
  'Beast Shank Heavy Boots',
  'Bitter Clasp Heavy Belt',
  'Bitter Fist Heavy Gloves',
  'Bitter Goad Battle Staff',
  'Bitter Song Spiculum',
  'Bitter Splitter Truncheon',
  'Bitter Weaver Grand Scepter',
  'Blood Barb Short Spear',
  'Bone Coat Trellised Armor',
  'Bone Quill Short War Bow',
  'Bramble Reaver Tomahawk',
  'Brimstone Horn Repeating Crossbow',
  'Brimstone Rend War Axe',
  'Brimstone Stinger Razor Bow',
  'Carrion Hew Fachion',
  'Carrion Mantle Gothic Plate',
  'Carrion Scalpel Stiletto',
  'Carrion Wrap Sharktooth Armor',
  'Corpse Cowl Shako',
  'Cruel Emblem Dragon Shield',
  'Cruel Hide Studded Leather',
  'Cruel Impaler Long Sword',
  'Cruel Scalpel War Sword',
  'Cruel Shield Scutum',
  'Death Grasp Bramble Mitts',
  'Death Song Rune Scepter',
  'Death Wyrmhide Nails Boots',
  'Demon Bite Battle Axe',
  'Demon Bite Flying Axe',
  'Demon Hew Dimensional Blade',
  'Demon Mangler Feral Axe',
  'Demon Visor Bone Helm',
  'Dire Star Reinforced Mace',
  'Doom Bite Claymore',
  'Doom Cowl Sallet',
  'Doom Harness Belt',
  'Doom Gnarl Gnarled Staff',
  'Doom Stinger Bone Knife',
  'Dread Cloak Russet Armor',
  'Dread Horn Circlet',
  'Dread Shell Ancient Armor',
  'Eagle Flight Hyperion Javellin',
  'Fiend Mantle Plate Mail',
  'Fiend Pelt Great Hauberk',
  'Gale Harp Arbalest',
  'Gale Skewer Winged Harpoon',
  'Gale Spell Long Staff',
  'Gale Visage Shako',
  'Ghoul Shield Sacred Rondache',
  'Glyph Knuckle Gauntlets',
  'Glyph Scratch Falcata',
  'Grim Dart Pilum',
  'Grim Mar Battle Sword',
  'Grim Mask Grand Crown',
  'Grim Plange Splint Mail',
  'Grim Song Blade Bow',
  'Grim Splitter Ancient Axe',
  'Grim Wrap Linked Mail',
  'Hailstone Needle Edge Bow',
  'Havoc Claw Light Gauntlets',
  'Havoc Crusher Scourge',
  'Imp Coat Diamond Mail',
  'Imp Fang Battle Dart',
  'Imp Gnarl Long Staff',
  'Imp Greaves Greaves',
  'Loath Mask Death Mask',
  'Pain Circlet Grand Conch',
  'Pain Cloak  Gothic Plate',
  'Pain Knuckle Bramble Mitts',
  'Plague Hide Breast Blade',
  'Plague Knell War Scepter',
  'Plague Splitter War Hammer',
  'Plague Stinger Short War Bow',
  'Raven Bite Small Crescent',
  'Raven Thrist Kris',
  'Shadow Bolt Double Bow',
  'Shadow Clasp Demonhide Sash',
  'Shadow Crack Jagged Star',
  'Shadow Hook Crown',
  'Shadow Mark Spiked Shield',
  'Shadow Needle Composite Bow',
  'Shadow Veil Shako',
  'Soul Casque Full Helm',
  'Spirit Fringe Light Belt',
  'Stone Hand Chain Gloves',
  'Stone Horn Short War Bow',
  'Storm Hew War Dart',
  'Storm Mantle Mage Plate',
  'Storm Rend Double Axe',
  'Storm Rock Bone Shield',
  'Storm Skewer Giant Sword',
  'Storm Veil Tiara',
  'Viper Pelt Dusk Shroud',
  'Wraith Ward Grim Shield');
